import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({subsets: ["latin"], weight:"500"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html style={{height: '100vh', padding: '0'}} lang="en">
      <body style={{height: '100vh', padding: '0', overflow: 'hidden'}} className={`${roboto.className}`}>
        <div className="flex flex-col h-screen">
          <Header/>
          {children}
        </div>
        </body>
    </html>
  );
}
