import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({subsets: ["latin"], weight:"500"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <head>
          <title>Weather app</title>
        </head>
        <body className={`${roboto.className}`}>
          
          <Providers>
            <div className="flex flex-col h-screen">
              <Header/>
              {children}
            </div>
          </Providers>
          
          </body>
        
    </html>
  );
}
